# Generated by Django 6.0.6 on 2026-07-27 15:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savingsgoal',
            options={'ordering': ['target_date']},
        ),
        migrations.RenameField(
            model_name='savingsgoal',
            old_name='name',
            new_name='goal_name',
        ),
        migrations.RenameField(
            model_name='savingsgoal',
            old_name='current_amount',
            new_name='saved_amount',
        ),
        migrations.RemoveField(
            model_name='savingsgoal',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='savingsgoal',
            name='description',
        ),
        migrations.RemoveField(
            model_name='savingsgoal',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=50),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='target_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
