# Generated by Django 6.0.6 on 2026-08-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='currency_preference',
            field=models.CharField(default='INR', max_length=3),
        ),
    ]
