# Generated by Django 6.0.6 on 2026-07-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['-income_date']},
        ),
        migrations.RenameField(
            model_name='income',
            old_name='date',
            new_name='income_date',
        ),
        migrations.AddField(
            model_name='income',
            name='title',
            field=models.CharField(default='Income Log', max_length=200),
        ),
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.CharField(choices=[('SALARY', 'Salary'), ('POCKET_MONEY', 'Pocket Money'), ('SCHOLARSHIP', 'Scholarship'), ('FREELANCING', 'Freelancing'), ('BUSINESS', 'Business'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
